### ISSUE TITLE
Admin page redirect to Yunohost sso

### ISSUE THREAD

**Issue by makotoworkshop** [YunoHost-Apps/dotclear2_ynh#13]
Hello !

Since YunoHost 3.7.0.1 update, when i try to go the administrator page (type /admin after blog url) the Yunohost sso is displayed instead.
So impossible to login to edit the blog.

Tested with Firefox 70.0.1 and Iridium Browser 2019.04

**Comment by kay0u** [comment]
Hi, and thank you for your report!

Since 3.7.0 is not stable yet, I can't merge the new system permission in master. But you can upgrade dotclear to support it:

```
sudo yunohost app upgrade dotclear2 -u https://github.com/YunoHost-Apps/dotclear2_ynh/tree/new-system-permission --debug
```

Tell me if it works

**Comment by makotoworkshop** [comment]
Thank you for this upgrade ! from 2.15.1~ynh1 to 2.15.2~ynh1

Unfortunately the issue still persist.

**Comment by kay0u** [comment]
Can you:

- Try an update again (I deleted the old permissions). With the same command as the one above.
- Ensure your user have the permission "`Dotclear2 (Admin)" in `Yunohost Web Admin` -> `Users` -> `Manage groups and permissions` -> `User specific permissions`

**Comment by makotoworkshop** [comment]
Great ! It's work, Thank you kay0u ^^

The permissions was already ok.
This second update has resolve the issue.

**Comment by kay0u** [comment]
I will keep this problem open until version 3.7.0 is stable.
