### ISSUE TITLE
Broken with the default editor dcCKEditor

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/dotclear2_ynh#32]
### Describe the bug

After installation, dotclear2 use the default editor dcCKEditor.
It doesn't work because of an error into the path to the editor itself

`Loading failed for the <script> with source “https://domain.tld/dotclear2/admin/index.phpindex.php?pf=dcCKEditor/js/ckeditor/config.js”.`

Notice the part with `admin/index.phpindex.php?` which obviously fail.

To disable that editor make it work again.

To solve the issue, the file `/var/www/dotclear2/inc/config.php` should not have the `index.php` at the end of the entry DC_ADMIN_URL and so should look like
`define('DC_ADMIN_URL', 'https://domain.tld/dotclear2/admin/');`

**Comment by kay0u** [comment]
Thank you for the report, #36 should fix this!
