### ISSUE TITLE
Uploaded files do not belong to the right group

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/dotclear2_ynh#37]
cf. forum thread in French: https://forum.yunohost.org/t/dotclear2-probleme-de-propriete/17535

Uploaded files belong to `$app:$app` while they should belong to `$app:www-data`.

Solutions:
- Set ACLs to upload directory
- Set group in PHP-FPM config file
- `chown $app:$app $final_path`

**Comment by Jaxom99** [comment]
looks like this got reversed in a later push, my recent install (working with php7.4 on latest ynh) has the same trouble)...
